import type { AnalysisDefinition, AnalysisKey, EvidenceProfile } from "@engine/shared/evidence";

const LAST_REVIEWED = "2026-08-24";

function profile(profile: Omit<EvidenceProfile, "lastReviewed">): EvidenceProfile {
  return Object.freeze({
    ...profile,
    lastReviewed: LAST_REVIEWED,
    limitations: Object.freeze([...profile.limitations]),
    referenceIds: Object.freeze([...profile.referenceIds]),
  });
}

function definition(definition: Omit<AnalysisDefinition, "evidence"> & { evidence: EvidenceProfile }) {
  return Object.freeze(definition);
}

export const ANALYSIS_CATALOG: readonly AnalysisDefinition[] = Object.freeze([
  definition({
    key: "saju",
    href: "/saju",
    titleKey: "hubSajuTitle",
    descKey: "hubSajuDesc",
    purpose: "traditional",
    tier: "cultural",
    evidence: profile({
      methodCategory: "traditional-symbolic",
      validationStatus: "experimental",
      targetPopulation: "전통 명리 해석을 참고하려는 사용자",
      normSource: null,
      instrumentVersion: "lunar-javascript/1.7.7",
      licenseStatus: "verified",
      limitations: ["전통 해석 체계이며 성격·건강·미래를 과학적으로 진단하지 않습니다."],
      referenceIds: ["saju"],
    }),
    durationMinutes: 5,
    itemCount: null,
    showOnMandala: true,
  }),
  definition({
    key: "astro",
    href: "/astro",
    titleKey: "hubAstroTitle",
    descKey: "hubAstroDesc",
    purpose: "traditional",
    tier: "cultural",
    evidence: profile({
      methodCategory: "astronomical-calculation",
      validationStatus: "experimental",
      targetPopulation: "천문 계산과 상징 해석을 함께 참고하려는 사용자",
      normSource: null,
      instrumentVersion: "astronomy-engine/2.1.19",
      licenseStatus: "verified",
      limitations: ["천체 위치 계산과 상징 해석을 구분하며, 해석은 예측 검사의 규준이 아닙니다."],
      referenceIds: ["astro"],
    }),
    durationMinutes: 3,
    itemCount: null,
    showOnMandala: false,
  }),
  definition({
    key: "tarot",
    href: "/tarot",
    titleKey: "hubTarotTitle",
    descKey: "hubTarotDesc",
    purpose: "traditional",
    tier: "cultural",
    evidence: profile({
      methodCategory: "traditional-symbolic",
      validationStatus: "experimental",
      targetPopulation: "상징 카드 리딩을 자기성찰에 활용하려는 사용자",
      normSource: null,
      instrumentVersion: "lumina-tarot-spread/2026-08",
      licenseStatus: "permission-required",
      limitations: ["카드 상징은 자기성찰을 돕는 해석 프레임이며 사실 판정이나 예측 규준이 아닙니다."],
      referenceIds: ["tarot"],
    }),
    durationMinutes: 2,
    itemCount: null,
    showOnMandala: true,
  }),
  definition({
    key: "numerology",
    href: "/numerology",
    titleKey: "hubNumerologyTitle",
    descKey: "hubNumerologyDesc",
    purpose: "traditional",
    tier: "cultural",
    evidence: profile({
      methodCategory: "traditional-symbolic",
      validationStatus: "experimental",
      targetPopulation: "수비학 상징을 자기성찰에 활용하려는 사용자",
      normSource: null,
      instrumentVersion: "lumina-numerology/2026-08",
      licenseStatus: "verified",
      limitations: ["숫자 상징 해석은 경험적 성격검사의 타당도·규준을 제공하지 않습니다."],
      referenceIds: ["numerology"],
    }),
    durationMinutes: 2,
    itemCount: null,
    showOnMandala: true,
  }),
  definition({
    key: "psychometrics",
    href: "/psychometrics",
    titleKey: "hubPsychometricsTitle",
    descKey: "hubPsychometricsDesc",
    purpose: "personality",
    tier: "scientific",
    evidence: profile({
      methodCategory: "psychometric",
      validationStatus: "validated-other-population",
      targetPopulation: "영어권 IPIP-50 참고 표본과 비교되는 성인 응답자",
      normSource: "IPIP 공개 참고 표본(한국 대표 규준 아님)",
      instrumentVersion: "IPIP-50/Goldberg-1992",
      licenseStatus: "verified",
      limitations: ["한국어 번역의 표적 집단 타당도와 한국 대표 규준을 보장하지 않습니다."],
      referenceIds: ["psychometrics"],
    }),
    durationMinutes: 10,
    itemCount: 50,
    showOnMandala: true,
  }),
  definition({
    key: "jungian",
    href: "/psychometrics/types",
    titleKey: "hubJungianTitle",
    descKey: "hubJungianDesc",
    purpose: "personality",
    tier: "scientific",
    evidence: profile({
      methodCategory: "derived-exploratory",
      validationStatus: "derived",
      targetPopulation: "IPIP-50 응답을 네 축으로 재표현하는 탐색 사용자",
      normSource: "IPIP 공개 참고 표본(한국 대표 규준 아님)",
      instrumentVersion: "lumina-jungian-type-lens/2026-08",
      licenseStatus: "permission-required",
      limitations: ["MBTI 공식 검사나 인증된 유형 판정이 아니며, Big Five 점수의 파생 요약입니다."],
      referenceIds: ["jungian", "psychometrics"],
    }),
    durationMinutes: 10,
    itemCount: 50,
    showOnMandala: true,
  }),
  definition({
    key: "darktriad",
    href: "/darktriad",
    titleKey: "hubDarkTriadTitle",
    descKey: "hubDarkTriadDesc",
    purpose: "personality",
    tier: "scientific",
    evidence: profile({
      methodCategory: "psychometric",
      validationStatus: "translation-not-validated",
      targetPopulation: "SD3 원척도와 한국 타당화 연구를 참고하는 성인 응답자",
      normSource: "내부 참고 표본(한국 3요인 구조 미확정)",
      instrumentVersion: "SD3-27/Jones-Paulhus-2014",
      licenseStatus: "permission-required",
      limitations: ["임상 진단·도덕성 판정이 아니며, 한국 연구에서 원척도의 3요인 구조가 그대로 재현되지 않았습니다."],
      referenceIds: ["darktriad"],
    }),
    durationMinutes: 7,
    itemCount: 27,
    showOnMandala: true,
  }),
  definition({
    key: "attachment",
    href: "/attachment",
    titleKey: "hubAttachmentTitle",
    descKey: "hubAttachmentDesc",
    purpose: "personality",
    tier: "scientific",
    evidence: profile({
      methodCategory: "psychometric",
      validationStatus: "experimental",
      targetPopulation: "ECR-R을 참고하는 성인 응답자",
      normSource: null,
      instrumentVersion: "ECR-R-36/Fraley-Waller-Brennan-2000 (비공식 축약 구현)",
      licenseStatus: "permission-required",
      limitations: ["현재 구현은 공식 ECR-R 문항·7점 척도·역채점 규칙과 일치하지 않아 실험용으로만 표시합니다."],
      referenceIds: ["attachment"],
    }),
    durationMinutes: 8,
    itemCount: 36,
    showOnMandala: true,
  }),
  definition({
    key: "horoscope",
    href: "/horoscope",
    titleKey: "hubHoroscopeTitle",
    descKey: "hubHoroscopeDesc",
    purpose: "daily",
    tier: "cultural",
    evidence: profile({
      methodCategory: "traditional-symbolic",
      validationStatus: "experimental",
      targetPopulation: "별자리·띠 상징을 일상 성찰에 참고하려는 사용자",
      normSource: null,
      instrumentVersion: "lumina-horoscope/2026-08",
      licenseStatus: "verified",
      limitations: ["일일 운세 문구는 상징적 성찰을 위한 콘텐츠이며 개인 사건의 확률 예측이 아닙니다."],
      referenceIds: ["horoscope"],
    }),
    durationMinutes: 1,
    itemCount: null,
    showOnMandala: true,
  }),
  definition({
    key: "compatibility",
    href: "/compatibility",
    titleKey: "hubCompatibilityTitle",
    descKey: "hubCompatibilityDesc",
    purpose: "traditional",
    tier: "cultural",
    evidence: profile({
      methodCategory: "derived-exploratory",
      validationStatus: "derived",
      targetPopulation: "두 사람의 전통 명리 관계 신호를 비교하려는 사용자",
      normSource: null,
      instrumentVersion: "lumina-synastry/2026-08",
      licenseStatus: "verified",
      limitations: ["관계의 질·지속 여부를 예측하거나 두 사람을 평가하는 검사가 아닙니다."],
      referenceIds: ["compatibility", "saju"],
    }),
    durationMinutes: 10,
    itemCount: null,
    showOnMandala: false,
  }),
] as const);

export function analysisDefinition(key: AnalysisKey): AnalysisDefinition {
  const definition = ANALYSIS_CATALOG.find((item) => item.key === key);
  if (!definition) throw new RangeError(`unknown analysis definition: ${key}`);
  return definition;
}
