import type { AnalysisDefinition, AnalysisKey, EvidenceProfile } from "@engine/shared/evidence";

const LAST_REVIEWED = "2026-08-24";

function profile(profile: Omit<EvidenceProfile, "lastReviewed">): EvidenceProfile {
  return Object.freeze({
    ...profile,
    lastReviewed: LAST_REVIEWED,
    limitations: Object.freeze([...profile.limitations]),
    referenceIds: Object.freeze([...profile.referenceIds]),
  });
}

function definition(definition: Omit<AnalysisDefinition, "evidence"> & { evidence: EvidenceProfile }) {
  return Object.freeze(definition);
}

export const ANALYSIS_CATALOG: readonly AnalysisDefinition[] = Object.freeze([
  definition({
    key: "saju",
    href: "/saju",
    titleKey: "hubSajuTitle",
    descKey: "hubSajuDesc",
    purpose: "traditional",
    tier: "cultural",
    evidence: profile({
      methodCategory: "traditional-symbolic",
      validationStatus: "experimental",
      targetPopulation: "전통 명리 해석을 참고하려는 사용자",
      normSource: null,
      instrumentVersion: "lunar-javascript/1.7.7",
      licenseStatus: "verified",
      limitations: ["전통 해석 체계이며 성격·건강·미래를 과학적으로 진단하지 않습니다."],
      referenceIds: ["saju"],
    }),
    durationMinutes: 5,
    itemCount: null,
    showOnMandala: true,
  }),
  definition({
    key: "astro",
    href: "/astro",
    titleKey: "hubAstroTitle",
    descKey: "hubAstroDesc",
    purpose: "traditional",
    tier: "cultural",
    evidence: profile({
      methodCategory: "astronomical-calculation",
      validationStatus: "experimental",
      targetPopulation: "천문 계산과 상징 해석을 함께 참고하려는 사용자",
      normSource: null,
      instrumentVersion: "astronomy-engine/2.1.19",
      licenseStatus: "verified",
      limitations: ["천체 위치 계산과 상징 해석을 구분하며, 해석은 예측 검사의 규준이 아닙니다."],
      referenceIds: ["astro"],
    }),
    durationMinutes: 3,
    itemCount: null,
    showOnMandala: false,
  }),
  definition({
    key: "tarot",
    href: "/tarot",
    titleKey: "hubTarotTitle",
    descKey: "hubTarotDesc",
    purpose: "traditional",
    tier: "cultural",
    evidence: profile({
      methodCategory: "traditional-symbolic",
      validationStatus: "experimental",
      targetPopulation: "상징 카드 리딩을 자기성찰에 활용하려는 사용자",
      normSource: null,
      instrumentVersion: "lumina-tarot-spread/2026-08",
      licenseStatus: "permission-required",
      limitations: ["카드 상징은 자기성찰을 돕는 해석 프레임이며 사실 판정이나 예측 규준이 아닙니다."],
      referenceIds: ["tarot"],
    }),
    durationMinutes: 2,
    itemCount: null,
    showOnMandala: true,
  }),
  definition({
    key: "numerology",
    href: "/numerology",
    titleKey: "hubNumerologyTitle",
    descKey: "hubNumerologyDesc",
    purpose: "traditional",
    tier: "cultural",
    evidence: profile({
      methodCategory: "traditional-symbolic",
      validationStatus: "experimental",
      targetPopulation: "수비학 상징을 자기성찰에 활용하려는 사용자",
      normSource: null,
      instrumentVersion: "lumina-numerology/2026-08",
      licenseStatus: "verified",
      limitations: ["숫자 상징 해석은 경험적 성격검사의 타당도·규준을 제공하지 않습니다."],
      referenceIds: ["numerology"],
    }),
    durationMinutes: 2,
    itemCount: null,
    showOnMandala: true,
  }),
  definition({
    key: "psychometrics",
    href: "/psychometrics",
    titleKey: "hubPsychometricsTitle",
    descKey: "hubPsychometricsDesc",
    purpose: "personality",
    tier: "scientific",
    evidence: profile({
      methodCategory: "psychometric",
      validationStatus: "validated-other-population",
      targetPopulation: "영어권 IPIP-50 참고 표본과 비교되는 성인 응답자",
      normSource: "IPIP 공개 참고 표본(한국 대표 규준 아님)",
      instrumentVersion: "IPIP-50/Goldberg-1992",
      licenseStatus: "verified",
      limitations: ["한국어 번역의 표적 집단 타당도와 한국 대표 규준을 보장하지 않습니다."],
      referenceIds: ["psychometrics"],
    }),
    durationMinutes: 10,
    itemCount: 50,
    showOnMandala: true,
  }),
  definition({
    key: "jungian",
    href: "/psychometrics/types",
    titleKey: "hubJungianTitle",
    descKey: "hubJungianDesc",
    purpose: "personality",
    tier: "scientific",
    evidence: profile({
      methodCategory: "derived-exploratory",
      validationStatus: "derived",
      targetPopulation: "IPIP-50 응답을 MBTI 네 선호 축으로 참고 해석하는 탐색 사용자",
      normSource: "IPIP 공개 참고 표본(한국 대표 규준 아님)",
      instrumentVersion: "lumina-mbti-style-analysis/2026-08",
      licenseStatus: "permission-required",
      limitations: ["공식 MBTI® 검사·문항·규준이 아니며, IPIP-50 Big Five 점수에서 파생한 비공식 참고 해석입니다."],
      referenceIds: ["jungian", "psychometrics"],
    }),
    durationMinutes: 10,
    itemCount: 50,
    showOnMandala: true,
  }),
  definition({
    key: "darktriad",
    href: "/darktriad",
    titleKey: "hubDarkTriadTitle",
    descKey: "hubDarkTriadDesc",
    purpose: "personality",
    tier: "scientific",
    evidence: profile({
      methodCategory: "psychometric",
      validationStatus: "translation-not-validated",
      targetPopulation: "SD3 원척도와 한국 타당화 연구를 참고하는 성인 응답자",
      normSource: "내부 참고 표본(한국 3요인 구조 미확정)",
      instrumentVersion: "SD3-27/Jones-Paulhus-2014",
      licenseStatus: "permission-required",
      limitations: ["임상 진단·도덕성 판정이 아니며, 한국 연구에서 원척도의 3요인 구조가 그대로 재현되지 않았습니다."],
      referenceIds: ["darktriad"],
    }),
    durationMinutes: 7,
    itemCount: 27,
    showOnMandala: true,
  }),
  definition({
    key: "attachment",
    href: "/attachment",
    titleKey: "hubAttachmentTitle",
    descKey: "hubAttachmentDesc",
    purpose: "personality",
    tier: "scientific",
    evidence: profile({
      methodCategory: "psychometric",
      validationStatus: "experimental",
      targetPopulation: "ECR-R을 참고하는 성인 응답자",
      normSource: null,
      instrumentVersion: "ECR-R-36/Fraley-Waller-Brennan-2000 (비공식 축약 구현)",
      licenseStatus: "permission-required",
      limitations: ["현재 구현은 공식 ECR-R 문항·7점 척도·역채점 규칙과 일치하지 않아 실험용으로만 표시합니다."],
      referenceIds: ["attachment"],
    }),
    durationMinutes: 8,
    itemCount: 36,
    showOnMandala: true,
  }),
  definition({
    key: "eq",
    href: "/eq",
    titleKey: "hubEqTitle",
    descKey: "hubEqDesc",
    purpose: "personality",
    tier: "scientific",
    evidence: profile({
      methodCategory: "psychometric",
      validationStatus: "translation-not-validated",
      targetPopulation: "Schutte et al.(1998) 성인 검증 표본과 비교되는 성인 응답자",
      normSource: "Schutte et al.(1998) 총점 요약통계 정규근사(실측 백분위표 아님)",
      instrumentVersion: "SSEIT-33/Schutte-1998",
      licenseStatus: "permission-required",
      limitations: [
        "정서지능을 수행으로 재는 능력검사가 아니라 스스로 보고한 특성 수준을 재는 자기보고 척도입니다.",
        "한국어 문항은 자체 번역이며 공식 한국어판으로 별도 타당화되지 않았습니다.",
        "백분위는 출판된 요약통계(평균·SD)에서 정규분포를 가정해 추정한 값이며 실측 백분위표가 아닙니다.",
        "하위요인은 출판 규준이 없어 원점수와 척도 내 상대 위치로만 표시하며, 총점 없이 단독 해석하면 원척도의 근거를 넘어섭니다.",
      ],
      referenceIds: ["eq"],
    }),
    durationMinutes: 8,
    itemCount: 33,
    showOnMandala: true,
  }),
  definition({
    key: "cognitive",
    href: "/cognitive",
    titleKey: "hubCognitiveTitle",
    descKey: "hubCognitiveDesc",
    // 자기보고가 아니라 정답이 있는 수행 문항이라 personality가 아니다 — 목적 축에서도 따로 선다.
    purpose: "ability",
    tier: "scientific",
    evidence: profile({
      methodCategory: "ability-sampling",
      validationStatus: "experimental",
      targetPopulation: "정답이 있는 추론 문항을 스스로 풀어 보려는 사용자",
      // 이 문항에 답한 표본이 존재한 적이 없다. 규준이 "아직 없다"가 아니라 "있을 수 없다".
      normSource: null,
      instrumentVersion: "lumina-cognitive-standardized-pilot/2026-08",
      licenseStatus: "verified",
      limitations: [
        "문항은 ICAR(Condon & Revelle, 2014)의 네 가지 형식만 따라 LUMINA가 직접 쓴 것이며 ICAR 원문 문항이 아닙니다.",
        "이 문항에 답한 규준 표본이 없어 백분위나 IQ 환산치를 낼 수 없습니다. 보고하는 값은 영역별·전체 정답률뿐입니다.",
        "16문항은 능력을 안정적으로 추정하기에 턱없이 적은 수입니다.",
        "임상 지능검사가 아니라 스스로를 살펴보기 위한 탐색이며, 결과는 도움 없이 혼자 풀었을 때만 의미가 있습니다.",
      ],
      referenceIds: ["cognitive"],
    }),
    durationMinutes: 15,
    itemCount: 20,
    showOnMandala: true,
  }),
  definition({
    key: "horoscope",
    href: "/horoscope",
    titleKey: "hubHoroscopeTitle",
    descKey: "hubHoroscopeDesc",
    purpose: "daily",
    tier: "cultural",
    evidence: profile({
      methodCategory: "traditional-symbolic",
      validationStatus: "experimental",
      targetPopulation: "별자리·띠 상징을 일상 성찰에 참고하려는 사용자",
      normSource: null,
      instrumentVersion: "lumina-horoscope/2026-08",
      licenseStatus: "verified",
      limitations: ["일일 운세 문구는 상징적 성찰을 위한 콘텐츠이며 개인 사건의 확률 예측이 아닙니다."],
      referenceIds: ["horoscope"],
    }),
    durationMinutes: 1,
    itemCount: null,
    showOnMandala: true,
  }),
  definition({
    key: "compatibility",
    href: "/compatibility",
    titleKey: "hubCompatibilityTitle",
    descKey: "hubCompatibilityDesc",
    purpose: "traditional",
    tier: "cultural",
    evidence: profile({
      methodCategory: "derived-exploratory",
      validationStatus: "derived",
      targetPopulation: "두 사람의 전통 명리 관계 신호를 비교하려는 사용자",
      normSource: null,
      instrumentVersion: "lumina-synastry/2026-08",
      licenseStatus: "verified",
      limitations: ["관계의 질·지속 여부를 예측하거나 두 사람을 평가하는 검사가 아닙니다."],
      referenceIds: ["compatibility", "saju"],
    }),
    durationMinutes: 10,
    itemCount: null,
    showOnMandala: false,
  }),
] as const);

export function analysisDefinition(key: AnalysisKey): AnalysisDefinition {
  const definition = ANALYSIS_CATALOG.find((item) => item.key === key);
  if (!definition) throw new RangeError(`unknown analysis definition: ${key}`);
  return definition;
}
