import type { AnalysisKey } from "@engine/shared/evidence";

/** BGM is intentionally opt-in; this key only describes the current route. */
export type BgmArea = "home" | AnalysisKey;

export interface BgmTrack {
  readonly area: BgmArea;
  readonly src: string;
}

/**
 * One original, loopable track per exploration lens. The files are generated by
 * scripts/generate-bgm.mjs and kept in public so playback never needs a server
 * request or a third-party audio service.
 */
export const BGM_TRACKS: Readonly<Record<BgmArea, BgmTrack>> = Object.freeze({
  home: { area: "home", src: "/audio/bgm/home.mp3" },
  saju: { area: "saju", src: "/audio/bgm/saju.mp3" },
  astro: { area: "astro", src: "/audio/bgm/astro.mp3" },
  tarot: { area: "tarot", src: "/audio/bgm/tarot.mp3" },
  numerology: { area: "numerology", src: "/audio/bgm/numerology.mp3" },
  psychometrics: { area: "psychometrics", src: "/audio/bgm/psychometrics.mp3" },
  jungian: { area: "jungian", src: "/audio/bgm/jungian.mp3" },
  darktriad: { area: "darktriad", src: "/audio/bgm/darktriad.mp3" },
  attachment: { area: "attachment", src: "/audio/bgm/attachment.mp3" },
  eq: { area: "eq", src: "/audio/bgm/eq.mp3" },
  cognitive: { area: "cognitive", src: "/audio/bgm/cognitive.mp3" },
  horoscope: { area: "horoscope", src: "/audio/bgm/horoscope.mp3" },
  compatibility: { area: "compatibility", src: "/audio/bgm/compatibility.mp3" },
});

const SHARE_KIND_AREA: Readonly<Record<string, BgmArea>> = Object.freeze({
  jungian: "jungian",
  bigfive: "psychometrics",
  darktriad: "darktriad",
  attachment: "attachment",
  eq: "eq",
  cognitive: "cognitive",
});

function stripLocalePrefix(pathname: string): string {
  if (pathname === "/en") return "/";
  if (pathname.startsWith("/en/")) return pathname.slice(3) || "/";
  return pathname || "/";
}

function matchesPath(pathname: string, root: string): boolean {
  return pathname === root || pathname.startsWith(`${root}/`);
}

/**
 * Resolve both landing and result URLs to the same lens. The order matters for
 * nested routes such as /psychometrics/types and /r/<data>/astro.
 */
export function bgmAreaForPath(pathname: string | null | undefined): BgmArea {
  const path = stripLocalePrefix(pathname ?? "/");
  if (path === "/") return "home";

  if (matchesPath(path, "/r")) {
    if (path.endsWith("/astro")) return "astro";
    if (path.endsWith("/today")) return "horoscope";
    return "saju";
  }

  if (matchesPath(path, "/s")) {
    const kind = path.split("/")[2] ?? "";
    return SHARE_KIND_AREA[kind] ?? "home";
  }

  if (matchesPath(path, "/psychometrics/types")) return "jungian";
  if (matchesPath(path, "/psychometrics")) return "psychometrics";
  if (matchesPath(path, "/saju") || matchesPath(path, "/characters")) return "saju";
  if (matchesPath(path, "/astro")) return "astro";
  if (matchesPath(path, "/tarot")) return "tarot";
  if (matchesPath(path, "/numerology")) return "numerology";
  if (matchesPath(path, "/darktriad")) return "darktriad";
  if (matchesPath(path, "/attachment")) return "attachment";
  if (matchesPath(path, "/eq")) return "eq";
  if (matchesPath(path, "/cognitive")) return "cognitive";
  if (matchesPath(path, "/horoscope")) return "horoscope";
  if (matchesPath(path, "/compatibility")) return "compatibility";

  return "home";
}

